#!/bin/bash
# Install updates
sudo yum update -y
# Install nginx
sudo yum install nginx -y
# Install node js & npm
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
. ~/.nvm/nvm.sh
nvm install 8.9.4
# Install git
sudo yum install git -y
